feat(sql): add finalNewline option
un-ts/prettier pull request #207
Opened 2022-07-22 14:14 UTC by frozenbonito

close #204

2022-07-22 15:18 UTC, frozenbonito commented
Thanks for comment.

> But should we reuse the `endOfLine` option from `prettier` core?

`sql-formatter` seems to support only `lf`.

https://github.com/sql-formatter-org/sql-formatter/blob/c59a163cfc93d9780480f4c262f9efa6fd1038ad/src/formatter/Layout.ts#L85-L86

It means the end of other each line is always `lf`, so I think the final line should be so too.

> The previous behavior could be a new option value `avoid` as the default value for compatibility.

In previous version, it always removes a final newline, doesn't preserve original.

There is a final newline here:
https://github.com/un-ts/prettier/blob/2c1f8c8d9de6702557bdc6273b7ea4f771e5c64e/packages/sql/test/fixtures/basic.sql#L10

After formatting, the final newline have been removed:
https://github.com/un-ts/prettier/blob/2c1f8c8d9de6702557bdc6273b7ea4f771e5c64e/packages/sql/test/__snapshots__/fixtures.spec.ts.snap#L29

2022-07-22 15:33 UTC, JounQin commented
> sql-formatter seems to support only lf.

We can adapt this in `prettier-plugin-sql` by simple `formatted.replace(/\r?\n/, ending)`

> In previous version, it always removes a final newline, doesn't preserve original.

That's why I say we should use `avoid` as the default value.

2022-07-22 17:21 UTC, frozenbonito commented
I added a new commit. Do you mean like this?

2022-07-22 17:38 UTC, JounQin requested changes

2022-07-22 17:38 UTC, JounQin commented on packages/sql/src/index.ts
> +        const ending = (() => {
I don’t think a immediate-called function is required here, in `case` just change `ending` instead, or a constant mapper.

2022-07-22 17:38 UTC, JounQin commented on packages/sql/src/index.ts
> +        { type, database, finalNewline, endOfLine, ...options }: SqlOptions,
No need to add `finalNewLine` anymore.

2022-07-22 17:38 UTC, JounQin commented on packages/sql/src/index.ts
> +        return finalNewline && !formatted.endsWith(ending)
```suggestion
        return endOfLine != 'auto' && !formatted.endsWith(ending)
```

2022-07-22 18:42 UTC, frozenbonito commented
Hmm, I think it is a strange that `endOfLine` affects final newline.

In addition, if this plugin respects `endOfLine`, I think it should preserve original line ending on `auto` same as `prettier`.

> "auto" - Maintain existing line endings (mixed values within one file are normalised by looking at what’s used after the first line)

Acutually, however, even if the original line ending is `crlf`, it will be replaced with `lf` by `sql-formatter`.
This is an unexpected behavior for users.

2022-07-22 19:39 UTC, frozenbonito commented
All `crlf` will replaced with `lf` by `sql-formatter`, but `prettier` core replaces them with a value based `endOfLine` again.
The same is true for the final newline, `formatted + '\n'` works as expected without reference to `endOfLine`.

2022-07-22 19:46 UTC, frozenbonito commented
For that reason, I think we just need an option to control the final newline for this plugin.

2022-07-23 00:14 UTC, JounQin commented
> Hmm, I think it is a strange that endOfLine affects final newline.

Isn’t prettier core doing this also?

2022-07-23 12:47 UTC, JounQin commented
It seems there is no way to get original `auto` `endOfLine` value

https://github.com/prettier/prettier/blob/ab72a2c11c806f3a8a5ef42314e291843e1b3e68/src/common/end-of-line.js#L3-L9

So a new option seems really needed, thanks!

2022-07-23 13:14 UTC, JounQin commented
I'm thinking is there any user case to have no final new line support? Prettier always print final new line AFAIK.

2022-07-23 13:27 UTC, JounQin approved these changes

2022-07-23 13:28 UTC, merged

2022-07-23 13:28 UTC, JounQin commented
@frozenbonito Thanks for your contribution!

2022-07-23 13:31 UTC, frozenbonito commented
> I'm thinking is there any user case to have no final new line support? Prettier always print final new line AFAIK.

I agree with you.

Thank you  for refactoring and merging!